language: java
os: osx
jdk: openjdk13

cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
 - chmod +x gradlew
 - wget https://download.java.net/java/GA/jdk13.0.2/d4173c853231432d94f001e99d882ca7/8/GPL/openjdk-13.0.2_windows-x64_bin.zip
 - unzip openjdk-13.0.2_windows-x64_bin.zip

install: skip

script:
 - ./gradlew -b build-travis.gradle runtimeZip --warning-mode all --info

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_deploy:
 - git config --local user.name "Thykof"
 - git config --local user.email "thykof@protonmail.ch"
 - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
 - git tag $TRAVIS_TAG

deploy:
 provider: releases
 token: $token
 file:
  - "build/libs/uPMT.jar"
  - "build/uPMT-osx-x64.zip"
  - "build/uPMT-win-x64.zip"
 on: ci
 skip_cleanup: true