language: java

install: true

os: osx
jdk: openjdk11

before_install:
 - chmod +x gradlew

script:
 - ./gradlew build

before_deploy:
 - git config --local user.name "Thykof"
 - git config --local user.email "thykof@protonmail.ch"
 - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
 - git tag $TRAVIS_TAG

deploy:
 provider: releases
 token: $token
 file: "./build/libs/uPMT.jar"
 on: try-ci
 skip_cleanup: true

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
